version = 0.1
[default]
    [default.deploy]
        [default.deploy.parameters]
        stack_name = "whether-api"
        s3_prefix = "sam/builds"
        s3_bucket = "whether"
        region = "us-east-1"
        confirm_changeset = false
        capabilities = "CAPABILITY_IAM"
